<?xml version="1.0" encoding="utf-8" standalone="no"?>
<!DOCTYPE chatting [
<!ELEMENT Complete (BlogSection , title , author , email , time)>
<!ELEMENT BlogSection (title , author , email , time)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT time (#PCDATA)>
]>
<Complete>

<BlogSection>
<title>Stringology is Magic</title>
<author>
	amandeep
</author>
<email>2012ecs25@smvdu.ac.in</email>
<time>1</time>
</BlogSection>

<BlogSection>
<title>I don't know</title>
<author>
	amandeep
</author>
<email>2012ecs25@smvdu.ac.in</email>
<time>2</time>
</BlogSection>

<BlogSection>
<title>Usable security</title>
<author>
	amandeep
</author>
<email>2012ecs25@smvdu.ac.in</email>
<time>3</time>
</BlogSection>

<BlogSection><title>Hill Climb Racing</title><author>Amandeep Gupta</author><email>2012ecs25@smvdu.ac.in</email><time>October 29, 2014, 12:32 pm</time></BlogSection>
<BlogSection><title>tirth</title>
<author>tirth</author>
<email>tirth@gmail.com</email>
<time>October 30, 2014, 6:06 am</time>
</BlogSection>
<BlogSection><title>Gekkan Shoujo Nozaki-kun Specials</title>
<author>tirth</author>
<email>tirth@gmail.com</email>
<time>October 30, 2014, 6:08 am</time>
</BlogSection>
<BlogSection><title>Cdknv</title><author>Amandeep Gupta</author><email>2012ecs25@smvdu.ac.in</email><time>October 30, 2014, 6:20 am</time></BlogSection></Complete>
